### ISSUE TITLE
Grant Sentry access to team

### ISSUE THREAD

**Issue by thibaudcolas** [wagtail/guide#108]
Same as people who have Heroku access currently – Editor Guide team in GitHub: https://github.com/orgs/wagtail/teams/editor-guide.

**Comment by RealOrangeOne** [comment]
The Sentry application currently sits in Torchbox's Sentry account, which due to SSO requirements can't have external users added to it.

**Comment by RealOrangeOne** [comment]
I've removed the integration from Torchbox's account, instead using the Sentry Heroku app. This means anyone with access to the Heroku app can see Sentry. The featureset is more limited (especially around notifications) but it works.

If we're finding we need more from it, we can either upgrade or reconsider the setup.
