### ISSUE TITLE
Site launch plan in time for Wagtail 4.1 release

### ISSUE THREAD

**Issue by thibaudcolas** [wagtail/guide#136]
For initial estimates, see #109.

- Target soft launch: Thursday 27/10/2022
- Traffic expected starting from Wagtail 4.1 release date (tentative: Tuesday 01/11/2022)

## w/c 17/10

Theme: getting closer to feature-complete & content-complete

- [x] #84 
- [x] #69 
- [x] #62
- [x] #110 
- [x] #86 
- [x] #76 
- [x] #100
- [x] #85
- [x] Grant Sentry access to team – Torchbox only (see #108)

## 24/10 - 26/10

Theme: feature-complete & content-complete

- [x] #125
- [x] #124 
- [x] #128 
- [x] #90
- [x] #138
- [x] #67
- [x] #139 
- [x] #127

## 27/10 - 28/10

Soft-launch: get the site live and start publicly sharing its existence

- [x] #92
- [x] #137
- [x] #140
- [x] #91
- [x] #107
- [ ] #106
## 31/10

Soft launch phase 2: Direct Wagtail 4.1 users to new website

- [ ] #126
- [ ] #101
- [ ] #102
- [ ] #134

## Post-launch

Final migration: fully replace existing Guide site in documentation

- [x] #108
- [ ] Placeholder

**Comment by thibaudcolas** [comment]
Marking as `help wanted` as I’d love feedback on whether this covers it all or not.

**Comment by thibaudcolas** [comment]
And we’re launched!

**Comment by lb-** [comment]
Yay! Incredible stuff everyone!
