### ISSUE TITLE
Words for translation

### ISSUE THREAD

**Issue by nicklee** [wagtail/guide#146]
A list of the hardcoded language throughout the site:

### Header

- Wagtail user guide
- User guide
- Toggle the search form
- Search
- Quick links
- Skip to main content

### Feedback widget

- Was this page helpful?
- Help us improve by telling what you missed
- Submit
- happy
- unhappy

### Footer

- About this guide
- Learn why we structured our documents like this
- Help improve this guide
- Contribute to open source with no coding experience needed
- Visit Wagtail.org for more resources and Wagtail news

### Homepage

- This documentation is written for anyone creating content or managing content production in Wagtail. It covers everything you can expect when using a standard Wagtail site.

### Content page

- On this page

**Comment by lb-** [comment]
Is the plan to put all this into a translatable snippet? Or maybe a bunch of fields on the home page model?
