### ISSUE TITLE
Accessibility audit findings

### ISSUE THREAD

**Issue by thibaudcolas** [wagtail/guide#150]
- [x] No need for the extra aria-label on https://github.com/wagtail/guide/blob/main/apps/search/templates/search/search.html
- [ ] Shouldn’t use a h2 for alert blocks as we can’t tell from the code alone whether they are within a section of the content or not https://github.com/wagtail/guide/blob/main/apps/core/templates/core/blocks/alert.html
- [ ] Feedback form heading should be a h2 https://github.com/wagtail/guide/blob/main/apps/core/templates/components/feedback.html

**Comment by nicklee** [comment]
Fixed in:

https://github.com/wagtail/guide/pull/169

**Comment by Scotchester** [comment]
I set #169 to close this issue, which I only noticed a few minutes ago, so that we can focus on the more extensive list I've been building in #76.
