### ISSUE TITLE
Use appropriate content licence in Guide footer

### ISSUE THREAD

**Issue by lb-** [wagtail/guide#164]
Currently the Wagtail guide footer says

> © Copyright 2022, Hitansh Shah and contributors

![Screenshot_20221020-213527](https://user-images.githubusercontent.com/1396140/196957502-9d0aa64a-2769-4dde-92b5-4f9634e3561c.png)

I understand this was from the original work and also acknowledges the epic start that @Hitansh-Shah made. 

However I think that the content on this site should at a minimum use the same liberal BSD licence as the code. https://github.com/wagtail/guide/blob/main/LICENSE

Alternatively we should consider the content, in isolation having a creative commons licence in its most liberal form. 

Either CC0 -https://creativecommons.org/share-your-work/public-domain/cc0/

Or potentially the basic one with attribution required https://creativecommons.org/licenses/

I do think we should acknowledge the contribution and contributors by name ( see https://github.com/wagtail/guide/issues/66 ) but think it's important we ensure the content on this new guide matches the same copyright licence as the Wagtail docs & platofm it's based on.

## Proposal

We use the same licence note in the footer as Mozilla's 'how do I Wagtail' - https://foundation.mozilla.org/en/docs/how-do-i-wagtail/

>  Content available under a [Creative Commons Attribution 4.0 International license](https://creativecommons.org/licenses/by/4.0/) (CC-BY)

**Comment by lb-** [comment]
Just realised the Wagtail docs have a copyright statement as follows

> © Copyright 2022, Torchbox and contributors 

So maybe I'm wrong about this and we should have a copyright statement, I just don't understand how that aligns with the licence used in the code (especially for Wagtail docs which are in files in that code). 

![Screenshot_20221020-232520](https://user-images.githubusercontent.com/1396140/196961534-e834d03c-ac2d-439c-86c5-d841fe285056.png)

**Comment by lb-** [comment]
I think `CC0` would be also a nicer option for the content.

**Comment by lb-** [comment]
Have raised this with the core team for additional feedback.

**Comment by activus-d** [comment]
@lb @thibaudcolas please review this:

## Copyright licensing
There are no rights reserved for this user guide documentation. There are no explicit permission requirements for using, distributing, remixing, adapting or building on its content. All of it is in the public domain and may be used, distributed, remixed, adapted, and built upon for private and commercial purposes to the fullest extent permitted law.

### Licensing grounds
The content of this user guide is not restricted in accordance with open source principles. The purpose of this is to facilitate innovation by encouraging open collaboration that is flexible.

### Liabilities
The contributors to this user guide documentation assume no responsibility or liability for any damages resulting from errors or omissions in the content. All content in this user guide documentation is provided on an "as-is" basis and no guarantee is provided as to completeness, accuracy, or timeliness.

**Comment by thibaudcolas** [comment]
Done!

**Comment by lb-** [comment]
Thanks all for this - it's great to clearly articulate that this is a community resource and hopefully the remixes of it will be epic.

**Comment by lb-** [comment]
Note to self - might be worth raising a similar issue for the Sphinx Wagtail theme docs) & Wagtail docs.
