### ISSUE TITLE
Screenshots bleed into background

### ISSUE THREAD

**Issue by allcaps** [wagtail/guide#166]
@benenright @thibaudcolas 

Screenshots bleed into the background. Especially the Wagtail header (grey on grey). The header is almost invisible.

During GSOC we tried to addressed bleeding screenshots (white-on-white) by changing the the page background from _white_ to a _very light purple_: _**This 'fix' doesn't work**_.

# Before/after 1
A screenshot applying drop shadows. Dropshadows give natural borders. It makes screenshots stand out.
> Please open images in their actual size to inspect the effects.

<img width="3008" alt="Screenshot 2022-10-20 at 15 09 33" src="https://user-images.githubusercontent.com/1969342/196959479-00fd062e-064d-42e3-bce3-cbf4fc4d117a.png">

# Before/after 2
If we accept drop shadows as a solution, we can also drop the purple background and use a white background. To illustrate:

<img width="3008" alt="Screenshot 2022-10-20 at 15 13 30" src="https://user-images.githubusercontent.com/1969342/196960549-4d80dccb-33b9-44ea-8698-e3e44cdf932c.png">

I find this much easier for the eyes. And easier to consume. Friendlier. The screenshots appear natural. The contents of screenshots now 'hang from the site header'. The natural anchor is restored. 

With this change, the guides styling doesn't disturb the screenshot contents.

My suggestion:
1. Use drop shadows on screenshots (all images in the content section).
2. Change te background from light purple to white.

Ref, for the drop shadow I used:
```
    box-shadow: 0 2px 12px 0 rgb(0 0 0 / 20%);
    border-radius: 4px;
    border: 1px solid #e4e4e4;
```

PS: I know drop shadows are not in the Wagtail Style Guide. To me it is justified to allow them here as they are minimal, yet distinctive.

# Update
Just realised that the info/warning blocks use drop shadow too.

**Comment by Scotchester** [comment]
+1 to shadowing the screenshots, but I like the light purple BG :)

**Comment by allcaps** [comment]
Not really, #115 is a bug. This ticket is on the visual effect.

With bleeds into background, I mean the optical effect of an image which primarily consists of colours of the background, without a clear boarder.

The purple bg was created to solve the issue, but doesn't.

**Comment by VictoriaAjala** [comment]
@lb this seems like a good feature to add. I'd create a PR for it @allcaps

**Comment by allcaps** [comment]
@VictoriaAjala Yes, go for it!

Can you:

1. Keep the drop shadow for info/warning blocks identical, for consistency?
2. Make the drop shadow in a way that it is visible on the top-left and bottom-right of the element? See my example code.

**Comment by VictoriaAjala** [comment]
@allcaps @lb- I have fixed this issue https://github.com/wagtail/guide/pull/181
