### ISSUE TITLE
Request that Mozilla's 'How do I Wagtail' updates their link to the user guide 

### ISSUE THREAD

**Issue by lb-** [wagtail/guide#174]
https://foundation.mozilla.org/en/docs/how-do-i-wagtail/

This site has a link to the Docs user guide but it would be good to request that Mozilla update this link to this new user guide (when launched). 

Not sure if that content is on GitHub or maybe managed somewhere else. 

![Screenshot_20221021-213710](https://user-images.githubusercontent.com/1396140/197187545-3b5ce192-25d4-46bf-8dfb-4612f4a89063.png)

**Comment by VictoriaAjala** [comment]
@lb- what link should the current link be updated to??

**Comment by thibaudcolas** [comment]
This seems to me like something we can live with, so I’ll close this now.
