### ISSUE TITLE
Undocumented (for editors) revisions feature

### ISSUE THREAD

**Issue by yhoiseth** [wagtail/guide#176]
### Is your proposal related to a problem?

I can't find any documentation for the revisions/diff/show changes feature. (It seems like I'm [not the only one](https://wagtailcms.slack.com/archives/C81FGJR2S/p1574156164091000).) I would expect to find it either

- as a section called e.g. "Managing revisions" under [Using Wagtail: an Editor’s guide](http://docs.wagtail.io/en/v2.7/editor_manual/index.html); or
- under [Editing existing pages](http://docs.wagtail.io/en/v2.7/editor_manual/editing_existing_pages.html).

### Describe the solution you'd like

A documentation section/article in one of the places mentioned above.

### Describe alternatives you've considered

I can't think of any other good ideas.

### Additional context

It might be relevant to mention the current limitations (#5711).

**Comment by lb-** [comment]
Moved from Wagtail repo to this Guide project.

**Comment by lb-** [comment]
https://github.com/wagtail/wagtail/pull/9466 - documentation update PR in Wagtail core for this. 

Not sure if we should close that PR and just add the content in the new site via the CMS.

**Comment by jadesola123** [comment]
Thank you for the feedback Ben @lb-

**Comment by thibaudcolas** [comment]
Now added at https://guide.wagtail.org/en-latest/how-to/creating-and-editing-pages/#managing-revisions. Thank you all!
