### ISSUE TITLE
Dark mode support

### ISSUE THREAD

**Issue by thibaudcolas** [wagtail/guide#180]
Suggested in https://github.com/wagtail/guide/discussions/116#discussioncomment-3944159 by @softkeldozy. This would indeed be _pretty cool_.

**Comment by lb-** [comment]
Here is the main code as implemented for the Sphinx theme, has gone through a few round of 'bugs' so should be hopefully a good starting point.

**Script**
https://github.com/wagtail/sphinx_wagtail_theme/blob/main/js/blocking.js

**Toggle button**
https://github.com/wagtail/sphinx_wagtail_theme/blob/828090a7405f04197e3d361ccbfe3c1a3a1cf34e/sphinx_wagtail_theme/layout.html#L132-L142

**Toggle button click listener**
https://github.com/wagtail/sphinx_wagtail_theme/blob/828090a7405f04197e3d361ccbfe3c1a3a1cf34e/js/theme.js#L60-L65

**Styles overrides for dark mode**
https://github.com/wagtail/sphinx_wagtail_theme/blob/main/sass/_darkmode.scss

**Comment by thibaudcolas** [comment]
Thank you LB, that helps _a lot_.

Here is a fancy toggle which Ben designed: https://areweheadlessyet.wagtail.org/

**Comment by nicklee** [comment]
MR added here: https://github.com/wagtail/guide/pull/197

**Comment by nicklee** [comment]
The mobile header area is becoming a little crowded, but feel like this is OK for now, would be good to revisit post-launch

![Screenshot 2022-10-25 at 12 12 52](https://user-images.githubusercontent.com/298766/197758640-07cd3019-0337-431c-adf7-027ae6022faa.png)
![Screenshot 2022-10-25 at 12 12 55](https://user-images.githubusercontent.com/298766/197758647-206c6039-4f88-49df-8eae-c5c18bbaa248.png)
