### ISSUE TITLE
Translating table of contents

### ISSUE THREAD

**Issue by saevarom** [wagtail/guide#182]
How will we translate the `table_of_contents` field on `ContentPage`? See for example https://guide.wagtail.org/is-latest/tutorials/getting-started/ where I've translated the available content to Icelandic, but the table of contents remains in English.

I can't see that this has been handled in #175 and I'm not sure why this field does not show up in the `wagtail-localize` interface.

What would be the best strategy to translate this type of data? I'm not sure there is a good way to handle it in Wagtail. 
Perhaps skip translations by dynamically extracting the headlines in Javascript instead of doing it on save?

**Comment by allcaps** [comment]
Ha! That worked via `apps.core.models.content.ContentPageForm.clean` and `apps.core.models.content.ContentPageForm.create_table_of_contents`. But that doesn't get called with Wagtail Localize. 🤔

**Comment by saevarom** [comment]
#206 fixes the problem only partially. 
So now I have Icelandic headings in the table of contents here: https://guide.wagtail.org/is-latest/tutorials/getting-started/#innskraning

But all the anchor id's in the body blocks are in english, so the links point to non-existent anchors.

**Comment by laymonage** [comment]
@saevarom Sorry, I missed that, should've actually clicked on the link when testing! Thanks for the report.

Workaround is here: https://github.com/wagtail/guide/pull/217

Not sure if it's something that we can fix properly, or if it's something that needs to be fixed upstream in wagtail-localize. Might be related: https://github.com/wagtail/wagtail-localize/issues/261
