### ISSUE TITLE
In page anchor links sometimes don't work

### ISSUE THREAD

**Issue by nicklee** [wagtail/guide#201]
Example here:
https://guide.wagtail.org/en-latest/how-to/copying-and-aliasing-pages/#copying-pages 

When clicking copying pages, you don't get anchored down the page as the id doesn't match.

The ID on the heading is `draftjs_exporterenginesstringelt-object-at-0x7fba786ee680` so it looks like drafttail is doing something weird.

**Comment by laymonage** [comment]
This seems to happen if the heading contains subelements, e.g. if you use bold/italic inside the heading. Fix in #225.
