### ISSUE TITLE
Search Button Icon Cursor Pointer Not Showing

### ISSUE THREAD

**Issue by softkeldozy** [wagtail/guide#207]
The **search button** has no cursor pointer effect

**Comment by lb-** [comment]
I do not think this is a problem, buttons normally should not have the cursor. I know that many sites use this though.

See 

* https://ux.stackexchange.com/questions/105024/why-dont-button-html-elements-have-a-css-cursor-pointer-by-default
* https://medium.com/simple-human/buttons-shouldnt-have-a-hand-cursor-b11e99ca374b
* https://developer.mozilla.org/en-US/docs/Web/CSS/cursor#usage_notes (default cursor for links is pointer but not buttons)

**Comment by softkeldozy** [comment]
Ok, thanks for the guide
