### ISSUE TITLE
Search & menu toggle (burger) button are different sizes

### ISSUE THREAD

**Issue by lb-** [wagtail/guide#211]
Not a huge problem but it would be nice if the two buttons next to each other (especially on mobile breakpoint) would be the same size.

* Search button is 42x42px
* Burger button is 40x30px

I do not think the icons need to be the same size, but rather the button target area should be the same.
Additionally, the focus outline transition is slightly longer on the search button for some reason (see recording).

## Screen reader

| Search | Burger |
|---|----|
|<img width="1333" alt="Screen Shot 2022-10-26 at 7 30 37 pm" src="https://user-images.githubusercontent.com/1396140/197992214-d152aeb7-51f1-4ba4-a75f-70e9581fb399.png">| <img width="1336" alt="Screen Shot 2022-10-26 at 7 30 49 pm" src="https://user-images.githubusercontent.com/1396140/197992276-45e680a5-6424-4604-9836-4e5959e66c99.png">|

## Recording

https://user-images.githubusercontent.com/1396140/197993212-b065b511-d017-4b1d-ac20-746d185cc94b.mp4

**Comment by VictoriaAjala** [comment]
@lb- i have already created a PR for this issue.
