### ISSUE TITLE
Icelandic translation

### ISSUE THREAD

**Issue by thibaudcolas** [wagtail/guide#212]
Just opening this for tracking purposes.

**Comment by thibaudcolas** [comment]
Flagging this for later – I assume we’ll get to this as part of content sync once the wagtail-localize issues are fixed:


- [ ] For https://guide.wagtail.org/is-latest/releases/new-in-wagtail-41/, the slug should be updated to `new-in-wagtail-4-1`.

**Comment by saevarom** [comment]
The slug is already `new-in-wagtail-4-1`

Do we need this issue still?

**Comment by thibaudcolas** [comment]
Indeed it is, weird! We probably don’t.
