### ISSUE TITLE
Content update - Copying existing pages

### ISSUE THREAD

**Issue by lb-** [wagtail/guide#219]
* The content from `docs/editor_manual/copying_aliasing_existing_pages.md` has had some updates on Wagtail main that would be good to incorporate into the new content on the Wagtail guide, mostly grammar fixes.
* See https://github.com/wagtail/wagtail/pull/9456

Just wanted to flag this as we are in limbo with deletion of the files on main but still getting some pull requests for changes.

_Originally posted by @lb- in https://github.com/wagtail/wagtail/pull/9456#pullrequestreview-1157275295_

**Comment by thibaudcolas** [comment]
Done!
