### ISSUE TITLE
add pre-commit to guide 

### ISSUE THREAD

**Issue by VictoriaAjala** [wagtail/guide#228]

**Comment by VictoriaAjala** [comment]
i'd like to work on it??

**Comment by Scotchester** [comment]
Thank you for the ida, @VictoriaAjala, but I don't think use of pre-commit falls under the mission of the Wagtail User Guide, which is solely for editors using the Wagtail admin UI. Maybe it would be worth considering in the Wagtail core docs, which are targeted at developers? If so, feel free to open an issue/PR on https://github.com/wagtail/wagtail with your proposed content.
