### ISSUE TITLE
Alert block needs to display alert type label instead of value

### ISSUE THREAD

**Issue by thibaudcolas** [wagtail/guide#237]
On https://github.com/wagtail/guide/blob/118b098910e057a88a5f7d535493426807db6f35/apps/core/templates/core/blocks/alert.html#L7

We display the `alert_type`’s identifier rather than the label. This is problematic for languages other than English, as the text will appear in English.

**Comment by VictoriaAjala** [comment]
So we should display the label right @thibaudcolas
