### ISSUE TITLE
I have a few observations and suggestions for the Wagtail User guide

### ISSUE THREAD

**Issue by EigegeIce** [wagtail/guide#241]
I looked at the guide and noticed it's bulky and from research most people have low attention spans.

1. I recommend maybe a demo video of how to set up a Wagtail website should be uploaded after the word content on the site.
2. I recommend demonstration videos all through the guide as pictures might not be enough to explain how the process goes from one point to another

**Comment by Scotchester** [comment]
Thank you for the feedback, @EigegeIce, and for posting more of it in the Discussion thread. I will close this issue now to keep the discussion concentrated there.
