### ISSUE TITLE
Invalid redirect for Wagtail Admin when browser language is not English

### ISSUE THREAD

**Issue by rluechinger** [wagtail/guide#262]
**Steps to reproduce**
1. Set your browser language to German
2. Open https://guide.wagtail.org/admin 

**Expected result**
Login view for Wagtail Admin is shown

**Actual Result**
Request is redirected to https://guide.wagtail.org/de-latest/admin/ which results in a 404

_Workaround: Set browser language to English to acccess the admin_

**Comment by saevarom** [comment]
Looks like this is a side effect of the locale handling middle `ValidateLocaleMiddleware`
