### ISSUE TITLE
Language picker inactive when user is redirected to 404 page

### ISSUE THREAD

**Issue by rluechinger** [wagtail/guide#263]
**Steps to reproduce**
1. Set your browser language to german
2. Enter https://guide.wagtail.org/
3. As German is probably already configured as available language but the German index is not yet published, I am redirected to https://guide.wagtail.org/de-latest/ which triggers a 404

**Expected result**
I can access the guide in another language by selecting i.e. English in the language picker.

**Actual result**
Other languages are not available in the Language Picker

**Comment by saevarom** [comment]
Thank you @rluechinger for reporting. 
I've opened a PR that proposes a solution:

- Activate english as default if a translated homepage in the requested locale is not found
- Removes the language selection button if it has no page to translate
