### ISSUE TITLE
Document how to make screenshots

### ISSUE THREAD

**Issue by allcaps** [wagtail/guide#274]

**Comment by Amalearner** [comment]
I want to work on this issue. Can I get more details on this?

**Comment by thibaudcolas** [comment]
@Amalearner that one isn’t a good fit for a newcomer! I’ll do this _in two weeks_. In the meantime, it’s all there: https://github.com/thibaudcolas/wagtail-tooling#documentation

**Comment by Amalearner** [comment]
Thank you 😊. I was mistaken at first. 😃.

**Comment by thibaudcolas** [comment]
I’ve added a baseline of documentation at https://guide.wagtail.org/en-latest/contributing/#images.
