### ISSUE TITLE
Search not supporting full text search?

### ISSUE THREAD

**Issue by benebun** [wagtail/guide#278]
Not sure how the search index works but I would have expected it to find pages with the search term "rich text":
https://guide.wagtail.org/en-latest/search/?query=rich+text
But I get 0 results, even though there are pages mentioning "rich text" e.g.
https://guide.wagtail.org/en-latest/how-to/creating-and-editing-pages/

**Comment by lb-** [comment]
I also just encountered this issue - searching for `comment` doesn't seem to find any of the pages that talk about commenting. 

https://guide.wagtail.org/en-latest/search/?query=comment

![Screenshot_20221129-174623](https://user-images.githubusercontent.com/1396140/204469454-0c8c378d-aeb2-4b77-9664-9405852b9513.png)

I would expect that this page at least would come up in the results.
https://guide.wagtail.org/en-latest/how-to/creating-and-editing-pages/#commenting
