### ISSUE TITLE
Add ability to report issue (provide feedback) on general pages

### ISSUE THREAD

**Issue by lb-** [wagtail/guide#279]
It would be good to be able to provide generic feedback on the home / about and search results pages. 

See search results - no 'Was this page helpful ' is shown. 

![Screenshot_20221129-174623](https://user-images.githubusercontent.com/1396140/204470532-21480bfe-45cf-4b45-af66-21ed4d55ca89.png)

**Comment by disperate** [comment]
Currently, the logic for storing feedback is implemented in the `serve()` method of the ContentPage by listening for POST requests. To enable this feature for every page type, I would prefer to move the feedback logic to a separate endpoint.

When saving feedback, a foreign key to a wagtail page is required. This will not be possible on the search result page as this is not implemented as a wagtail page. @laymonage do you have any preference on how this should be approached? I would address this by changing the feedback model to allow `null` values for this foreign key and additionally store the requested URL in a URLField.

**Comment by thibaudcolas** [comment]
I’ve added a feedback link within the footer which will hopefully be enough.
