### ISSUE TITLE
Wagtail User Guide Background Image Bug

### ISSUE THREAD

**Issue by andre-fuchs** [wagtail/guide#281]
Not sure how this is meant to look, but the text in front of the images here is not legible at all. 

### Pertinent section of the Wagtail docs

https://guide.wagtail.org/en-latest/how-to-guides/promote-search-results/

### Details
Firefox 105.0.3 on Pop!_OS

![Screenshot from 2022-11-29 20-27-56](https://user-images.githubusercontent.com/43378427/204630121-5a148b12-def1-4d6c-91b2-935e7f88d616.png)

**Comment by thibaudcolas** [comment]
Thanks for reporting @andre-fuchs. It looks like our "Note" / "Alert" blocks’ icons aren’t properly implemented, they’re missing a set width and height. For me in Firefox macOS the icons don’t display at all.
