### ISSUE TITLE
Add Wagtail guide to Awesome Wagtail 

### ISSUE THREAD

**Issue by lb-** [wagtail/guide#291]
https://github.com/springload/awesome-wagtail#open-source-sites

Would be good to list this site on Awesome Wagtail

**Comment by HimanshuGarg47** [comment]
I'd like to include it.

**Comment by HimanshuGarg47** [comment]
I have made a PR.  Please review it.
https://github.com/springload/awesome-wagtail/pull/197

**Comment by lb-** [comment]
https://github.com/springload/awesome-wagtail/pull/197 has been merged. thanks @HimanshuGarg47
