### ISSUE TITLE
Python fundamentals

### ISSUE THREAD

**Issue by activus-d** [wagtail/guide#296]
Python coding challenge by [Storm](https://github.com/stormheg)
Program a game where the user has to guess a random number generated by the program. The program gives hints if the user’s input is lower or higher than the random number. The game ends when the user's input is the same as the random number.
Conditions
- The program uses the command line interface.
- The random number is a number between 1 and 100 (inclusive).
- The program displays an error message if the input is not a number.
- The program displays a message if the input number is higher than the random number.
- The program displays a message if the input number is lower than the random number.
- The program ends if the input number is the same as the random number.
- The user gets infinite tries.

**Comment by activus-d** [comment]
## Solution
```
import random

def random_number_game():
    random_number = int(random.random() * 100)
    while True:
        print("Guess a number between 1-100")
        try:
            user_input = int(input())
            if user_input == random_number:
                print("Yay, you win!")
                break
            elif user_input > random_number:
                print("Too high Please try again.")
            elif user_input < random_number:
                print("Too low. Please try again.")
        except ValueError:
            print("Please enter a number")

random_number_game()
```

**Comment by SriramBharadwaj1** [comment]
hi, my name is Sriram Bharadawaj
mail id - sriram9217@gmail.com

I would like to complete this code if you can assign me to it
