### ISSUE TITLE
Site Data section on the sidebar is not referenced in the Guide

### ISSUE THREAD

**Issue by cedarworth** [wagtail/guide#327]
The Site Data section of the sidebar is not referenced in the [user guide](https://guide.wagtail.org/). It is important to include Site Data section on the Guides because it literally holds the link of all the data in it and that of Snippets section.
@thibaudcolas

**Comment by cedarworth** [comment]
The Site Data section contains the same data as the Snippets section. However, all the data in Snippets section, when clicked, get redirected to the page being handled by Site Data section. The Side Data section seems more important than the Snippets section.

![site_data](https://github.com/wagtail/guide/assets/111006348/85f38633-fa57-4a4e-9a47-4a3894a9f27b)
![snippets](https://github.com/wagtail/guide/assets/111006348/72da69d7-3fb0-45fe-99dc-c55e8af67ac8)

**Comment by Scotchester** [comment]
Thank you for suggesting this, @cedarworth, however Site Data is not a stock Wagtail feature. It is a custom snippet configuration that has been added by the developer(s) of the site you are working with. Therefore, they should not be documented in the general Wagtail User Guide.

**Comment by cedarworth** [comment]
This is well noted.
Thank you @Scotchester

**Comment by thibaudcolas** [comment]
What @Scotchester said :) If you want to document generic Snippets functionality that is very welcome, but for now I would recommend focusing on #325 until you have more understanding of Wagtail.

**Comment by cedarworth** [comment]
Thank you @thibaudcolas

**Comment by cedarworth** [comment]
> Thank you for suggesting this, @cedarworth, however Site Data is not a stock Wagtail feature. It is a custom snippet configuration that has been added by the developer(s) of the site you are working with. Therefore, they should not be documented in the general Wagtail User Guide.

Thanks for the feedback @Scotchester
