### ISSUE TITLE
Wagtail Blog Page is not Documented yet

### ISSUE THREAD

**Issue by Ozyugoo** [wagtail/guide#330]
I noticed that how to manage the blog page was not documented and I believe it should be documented. It would be nice if users could have a step-by-step guide on how to access the blog page, develop their posts, add images to the post, and publish them. 

![Blog-post-shot1](https://github.com/wagtail/guide/assets/113618136/cf865672-ab97-442e-b128-233e77b7b5d0)

![Blog-post-shot2](https://github.com/wagtail/guide/assets/113618136/8bab9629-0ed7-42a5-8c60-5fa9c5a3acc1)

**Comment by Ozyugoo** [comment]
@thibaudcolas I would like to work on this, if that's okay.

**Comment by Ozyugoo** [comment]
[blog post 2.docx](https://github.com/wagtail/guide/files/13188309/blog.post.2.docx)

**Comment by Ozyugoo** [comment]
## **Wagtail Blog Post User Guide**


![Blog-post-shot2](https://github.com/wagtail/guide/assets/113618136/bcc03612-a4b5-4225-bed9-811b85947745)


When I got admin right and wanted to create my first page, it was not easy to navigate, I was a bit confused. I created and deleted several of my pages before I was able to get the hang of things. This inspired me to write about this guide to help other users be able to navigate the blog post with ease.
From your **Dashboard** click on the **Pages** link at the left **sidebar** of the **dashboard**.


![userguide1](https://github.com/wagtail/guide/assets/113618136/88b92db7-be9c-4693-984e-c78a04263ad5)

Click on the **Pages** on top that has a **home icon** close to it.


![userguide2](https://github.com/wagtail/guide/assets/113618136/53406550-0723-400a-8179-8019229c283a)


**Click** on the **three horizontal dots** in front of **Root**, a dropdown will appear. On the **dropdown**, click on the **Add child page** button the it should take you to another page.


![userguide3](https://github.com/wagtail/guide/assets/113618136/4365a61c-d2eb-4b1d-86b0-c38a741fc588)


On this new page, select the type of page from the **Create a page in Root, Choose which type of page you’d like to create**. There are three links connected to the Blog: the Blog index page, the Blog page, and the Blog tag index page.


![userguide4](https://github.com/wagtail/guide/assets/113618136/a5d3f21e-ff0a-4bdb-b054-eddd3bf28e2e)


The Blog index page will lead to a page where to create the Page title and the Intro. The page title will be the title to display in the live space. While the Intro will be the introduction or subtitle for the page.
**Click** on the **Blog page** to create the actual Blog. On the Blog page, there are two links **Content** and **Promote**.


![userguide5](https://github.com/wagtail/guide/assets/113618136/74a91b58-50a9-4bbd-b754-d983d4d59686)


On the Content page, Use the **Tab** key to move through the fields of the blog page. The Page title should be as it would be in the live space.

### Blog information

This section is for the details of the blog which Includes:

**Post date:** This displays the date of publication. **Click** on the input box and **Select** the date to publish the post.

**Tags**: Add words or phrases that are relevant to your title on the **Tag** space. This will help with Search Engine Optimization(SEO).

**Authors**: Since it is possible for a space to have more than one admin, the Author section is a checkbox. **Tick** to select the name of the particular Author who worked on the blog post and it will display on the live page.

**Intro**: This is the subtitle for the page, in this field, the user is able to give the title a better description.

**Body**: The body is the area to write the content of the blog. **Type /** (forward slash) to insert a block. These include headings, bullets, numberings, images, links, horizontal lines, and embed a video.

### Gallery images

In this section, add images that are already saved in the collection folder to the page.
Once finished, use the **save draft** button to save it as a draft.
I hope this was helpful.

**Comment by thibaudcolas** [comment]
@Ozyugoo there’s a fundamental problem in understanding here. Wagtail itself doesn’t come with a blog page – this is something that would be set up for a specific site as needed.

**Comment by Ozyugoo** [comment]
> @Ozyugoo there’s a fundamental problem in understanding here. Wagtail itself doesn’t come with a blog page – this is something that would be set up for a specific site as needed.

I know this issue has been closed already, but I will like to learn and understand better what you meant by your reply. 
I was trying to point out that blog page was not documented on the user guide, it seems that I didn’t express my point well. 
Could you please explain further to help me understand better.

While I look for other features that are yet to be documented.
Thanks
