### ISSUE TITLE
Missing Documentation for Navigation Settings in Support Guide

### ISSUE THREAD

**Issue by nouman17610** [wagtail/guide#332]
User guide contains no content related to "how to update navigation settings. There is no information available for the navigation page.
![Editing-Navigation-settings-Wagtail](https://github.com/wagtail/guide/assets/112282629/7c8e4953-0f9f-40a4-88a3-6b88e8795b38)

**Why navigation page should be documented?**
Although it is a page for a simple 3 URLs but it is important for user to know about the purpose of this page. Without an information, user may not understand the functionality of the navigation settings page. Existing users find it easy to updates the URLS. New user find it difficult to understand the type of URLs required. Effective documentation can reduce the confusion of user while editing the URLs of social profiles. 
Documentating the navigation setting is important for future changes. Later on, this page may get more updates about navigation settings. Docs team would need less time to complete documentation for upcoming features in the navigation page. Furthermore, user guide must ensure consistency of documenting all the features. 

**How it should be documented?**
Documentation should follow these steps to document the navigation settings page

- Provide an overview of Navigation Setting page.
- Instruct user by step-by-step approach to complete edit the URLs.
- Explain the user about errors and issues during the process
- Give feedback at the end.

**Comment by Scotchester** [comment]
Hi @nouman17610,

Thank you for reporting this, but Navigation Settings is not a stock Wagtail feature. They are custom settings that have been added by the developer(s) of the site you are working with. Therefore, they should not be documented in the general Wagtail User Guide.
