### ISSUE TITLE
Browser-level UI settings (Accessibility features documentation)

### ISSUE THREAD

**Issue by ginandze** [wagtail/guide#333]
Browser-level UI settings

- [ ] Sidebar expanded/collapsed
- [ ] Rich text toolbar pinned/unpinned
- [ ] Minimap opened/closed
- [ ] Currently-open side panel

**Comment by ginandze** [comment]
**Browser-level UI settings**
**Sidebar expanded/collapsed**
By default, the sidebar is expanded. 
  
![image](https://github.com/wagtail/guide/assets/112075176/17163ee5-5a4d-4534-ac77-549db19c07fd)

To collapse it, simply click on the toggle button at the top-right of the sidebar. 
![image](https://github.com/wagtail/guide/assets/112075176/12e698d0-9d27-403b-b02c-a4ee709e173f)


**Rich text toolbar pinned/unpinned**
While on the edit screen, you may need to pin the rich text toolbar for easy access. To do this, highlight a piece of the text you are typing. The rich text toolbar will appear. 
 
![image](https://github.com/wagtail/guide/assets/112075176/37c8195e-0767-4cf0-ba42-b1f8e2bd484b)
Click on the pin at the top-right of this toolbar to pin it at the top of the text area.
![image](https://github.com/wagtail/guide/assets/112075176/66f20e0f-320c-4e35-9679-82769d8f5f49)


**Minimap opened/closed**
The page editor minimap is opened by default. To close it, click on the toggle button at the top-right of the minimap.
 
![image](https://github.com/wagtail/guide/assets/112075176/716bb5bd-0d8f-4d12-a4cf-3fce9d93896b)

**Currently-open side panel**
While on the edit screen, you can access the currently-open side panel by clicking on any of the items on the top-right taskbar menu, such as Status, Comments, Preview or History.
To close the side panel, click on the toggle button at the top of the side panel.
![image](https://github.com/wagtail/guide/assets/112075176/5b8ce1e8-1d53-42ca-b050-a47b0eb0d709)

**Comment by thibaudcolas** [comment]
@ginandze I think this should be done at the same time as #329. Please be mindful that screenshots are a lot of work to maintain. It’s not really sustainable for us to have as many as you suggest here.

**Comment by ginandze** [comment]
> @ginandze I think this should be done at the same time as #329. Please be mindful that screenshots are a lot of work to maintain. It’s not really sustainable for us to have as many as you suggest here.

Understood @thibaudcolas I'll work on this, thanks.
