### ISSUE TITLE
Text search (Accessibility feature documentation)

### ISSUE THREAD

**Issue by ginandze** [wagtail/guide#339]
Text search 
(Accessibility feature documentation)

**Comment by ginandze** [comment]
**Text Search**
On the **Dashboard**, you can find a Search field on the sidebar. You can use this field to search a piece of text in the whole website which can either be text from pages, Images (as image names), Documents or from Users.
![image](https://github.com/wagtail/guide/assets/112075176/c53c65bd-ec48-4272-9f22-9f31ba9e4519)
•	Click on the Search field and type in the word(s) you want to find. 
•	Press Enter on your keyboard. The search results will appear.
•	Click on the various options on the search results navbar to find your required results.

![image](https://github.com/wagtail/guide/assets/112075176/cb6c1c26-9d61-4cdc-a4dd-a969aa40a5aa)

**Comment by thibaudcolas** [comment]
This is already documented (https://guide.wagtail.org/en-latest/how-to-guides/find-your-way-around/#search-wagtail)
