### ISSUE TITLE
Collapsible Sections

### ISSUE THREAD

**Issue by cedarworth** [wagtail/guide#342]
The Collapsible sections are highly important as they house house so many sections. These important sections which would have taken so much space on the dashboard are now hidden thereby improving user experience.
Collapsible sections documentation do not require a new page. It should can be placed in [Find your way around](https://guide.wagtail.org/en-latest/how-to-guides/find-your-way-around/#the-sidebar) after the **Dashboard panels** section. @thibaudcolas , I believe we can include **[Link to specific collapsible sections](https://github.com/wagtail/guide/issues/343)** here too.

![collapsible sections](https://github.com/wagtail/guide/assets/111006348/27b0036c-460d-4b36-9c45-c79270efa71d)

**Comment by cedarworth** [comment]
**Collapsible Sections**

The **Collapsible sections** allow you  access to more sections.  The items on the **Sidebar** with collapsible sections are:
**Pages**
When you click pages, you have access to all pages you have created.
![pages](https://github.com/wagtail/guide/assets/111006348/af24693e-45d6-4b0e-ab64-6c8a047c41b8)

**Site Data**
> Footer Text
> Authors
When you click Site Data, it expands to show all the site data.
![siteData](https://github.com/wagtail/guide/assets/111006348/86c3e67d-64e0-4db8-bcae-e1182cc07edc)

**Reports** 
> Locked pages
> Workflows
> Workflow tasks
> Site history
> Aging pages
Clicking reports opens up the locked pages, workflows, workflow tasks, site history and  Aging pages.
![Reports](https://github.com/wagtail/guide/assets/111006348/2d3e029f-065e-4e9d-8147-d75554e3671b)

**Settings**
Settings section allows you to make adjustments to many sections such as:
> Workflows
> Workflow tasks
> Users
> Groups
> Sites
> Collections
> Redirects
> Navigation settings
![Settings](https://github.com/wagtail/guide/assets/111006348/879ab60e-6a3e-41b8-a7b9-a48c49624d29)

**Helps**
> What's new in Wagtail 5.1
> Editor Guide
Helps icon gives you access to the section about the current version of Wagtail and the editor guide.
![helps](https://github.com/wagtail/guide/assets/111006348/d32aca88-9eca-49e1-868b-6f732b9eb1c3)

**Profile name**
> Account
> Logout

![account](https://github.com/wagtail/guide/assets/111006348/0f3d6f47-98a1-4739-a00d-a8fc3dbd06be)
**Collapsible Sections**

The **Collapsible sections** allow you  access to more sections.  The items on the **Sidebar** with collapsible sections are:
**Pages**
When you click pages, you have access to all pages you have created.
![pages](https://github.com/wagtail/guide/assets/111006348/af24693e-45d6-4b0e-ab64-6c8a047c41b8)

**Site Data**
> Footer Text
> Authors
When you click Site Data, it expands to show all the site data.
![siteData](https://github.com/wagtail/guide/assets/111006348/86c3e67d-64e0-4db8-bcae-e1182cc07edc)

**Reports** 
> Locked pages
> Workflows
> Workflow tasks
> Site history
> Aging pages
Clicking reports opens up the locked pages, workflows, workflow tasks, site history and  Aging pages.
![Reports](https://github.com/wagtail/guide/assets/111006348/2d3e029f-065e-4e9d-8147-d75554e3671b)

**Settings**
Settings section allows you to make adjustments to many sections such as:
> Workflows
> Workflow tasks
> Users
> Groups
> Sites
> Collections
> Redirects
> Navigation settings
![Settings](https://github.com/wagtail/guide/assets/111006348/879ab60e-6a3e-41b8-a7b9-a48c49624d29)

**Helps**
> What's new in Wagtail 5.1
> Editor Guide
Helps icon gives you access to the section about the current version of Wagtail and the editor guide.
![helps](https://github.com/wagtail/guide/assets/111006348/d32aca88-9eca-49e1-868b-6f732b9eb1c3)

**Profile name**
> Account
> Logout

![account](https://github.com/wagtail/guide/assets/111006348/0f3d6f47-98a1-4739-a00d-a8fc3dbd06be)

**Comment by thibaudcolas** [comment]
See #343. You’ve spent a lot of time on this without understanding what "Collapsible sections" means. There is plenty of documentation about our main navigation / sidebar – please make sure to review existing docs before suggesting additions.
