### ISSUE TITLE
Link to specific collapsible sections

### ISSUE THREAD

**Issue by cedarworth** [wagtail/guide#343]
Link to specific collapsible sections are important for documentation. However, I believe documenting the specific link corresponding to a section under the **Collapsible sections** will be more appropriate. Otherwise, we can place the links immediately after the **Collapsible Sections** (which is also after **The Dashboard panels**) in [Find your way around](https://guide.wagtail.org/en-latest/how-to-guides/find-your-way-around/).  @thibaudcolas

**Comment by cedarworth** [comment]
**Link to specific collapsible sections**

**PAGES**
> [Pages](https://your-wagtail-portfolio.fly.dev/admin/pages/)

**SITE DATA**
> [Footer Text](https://your-wagtail-portfolio.fly.dev/admin/snippets/base/footertext/)
> [Authors](https://your-wagtail-portfolio.fly.dev/admin/snippets/blog/author/)

**REPORTS**
> [Locked pages](https://your-wagtail-portfolio.fly.dev/admin/reports/locked/)
> [workflow](https://your-wagtail-portfolio.fly.dev/admin/reports/workflow/)
> [ workflow tasks](https://your-wagtail-portfolio.fly.dev/admin/reports/workflow_tasks/)
> [Site history](https://your-wagtail-portfolio.fly.dev/admin/reports/site-history/)
> [Aging pages](https://your-wagtail-portfolio.fly.dev/admin/reports/aging-pages/)

**SETTINGS**
> [workkflows](https://your-wagtail-portfolio.fly.dev/admin/workflows/list/)
> [workflow tasks](https://your-wagtail-portfolio.fly.dev/admin/workflows/tasks/index/)
> [users](https://your-wagtail-portfolio.fly.dev/admin/users/)
> [groups](https://your-wagtail-portfolio.fly.dev/admin/groups/)
> [sites](https://your-wagtail-portfolio.fly.dev/admin/sites/)
> [collections](https://your-wagtail-portfolio.fly.dev/admin/collections/)
> [Redirects](https://your-wagtail-portfolio.fly.dev/admin/redirects/)
> [Navigation settings](https://your-wagtail-portfolio.fly.dev/admin/settings/base/navigationsettings/1/)

**HELPS**
> [what's New in wagtail](https://guide.wagtail.org/en-latest/releases/new-in-wagtail-5-1/)
> [Editor Gulde](https://guide.wagtail.org/en-latest/

**Comment by thibaudcolas** [comment]
@cedarworth those are not referred to as collapsible sections anywhere. I think you should make sure you understand what you’re reporting about before creating an issue.
