### ISSUE TITLE
Collapse/expand all

### ISSUE THREAD

**Issue by cedarworth** [wagtail/guide#344]
The documentation of Collapse/expand all is important. It allows the users to know they can have more room to work with by collapsing a section while working on another section on the same page.
@thibaudcolas

**Comment by cedarworth** [comment]
The **Collapse/expand all** allows you to make more room available by collapsing a section you are not currently working on thereby creating more room. You can also expand the section again as need arises.
![collapsibles](https://github.com/wagtail/guide/assets/111006348/c0d816ff-82ae-45dd-b2e1-1eb2f5a73caf)

**Comment by thibaudcolas** [comment]
@cedarworth I think there is a problem in understand as well. Please see my feedback on #342 / #343.
