### ISSUE TITLE
Wagtail Command Palette and Available Command Need Documentation

### ISSUE THREAD

**Issue by Ozyugoo** [wagtail/guide#349]
I noticed that Wagtail offers a cloud-based IDE on Gitpod where users can play with code and customize their site. This wonderful feature needs documentation so that users can easily navigate and explore their content.  

![Wagtail-IDE](https://github.com/wagtail/guide/assets/113618136/6eeb910e-fd14-443b-92cd-508bf3a6c703)

**Comment by Ozyugoo** [comment]
## **Command Palette and Common Commands.**


**Wagtail** offers a cloud-based **IDE** on **Gitpod** that incorporates the functions of VS Code. It is a one-click setup that abstracts all the hassle of setting up a development workspace with ease. It is incredible to save the local machine the space to download the command palette. The command palette requires the user to have a GitHub account and a browser.

### **These are Some Common Keyboard Shortcuts;**

**Open File:** Click the **three Horizontal Bars** on the top left of the editor and **Click** on **File**. Then **Click** on **Open File** or **Recent Folder** to open a file or folder.
**Explorer**: Use **Ctrl+Shift+E** to **open** the **file explorer** on the repository in focus.
**Search**: **Open** the **search panel**, Use **Ctrl+Shift+F**, and search for information in the directory.
**Version Control**: Press **Ctrl+shift+G** to open the version control panel for the Git Commands.
**Run and Debug**: Press **Ctrl+Shift+D** to open the debug and run panel.
**Extensions**: Press **Ctrl+Shift+X** to **open** and **install** extensions such as Git Lens, and Python (Pylance).

There is also a Testing and GitHub icon on the left sidebar, that leads to GitHub or test your code.

### **Some Common Commands:**

**Open File**: Go to **File**: **Open File** - Opens a file picker to open a specific file.
**New File**: From File **Click** on **New File** to **Create** a new file.
**Save File**: **File**: **Save** - Saves the current file or use **Ctrl+S**.
**Find**: **Go to Edit**, **Click** on **Find** - Opens the search panel to find text in files across the project.
**Replace**: **Go to Edit** **Click** on **Replace** - Opens the search panel to find and replace text in files across the project.

### **Version Control (Git) Commands:**

**Git Pull**: **Click** on the **Icon** with **three mouths**, and **click** **Pull** to Pull changes into the current branch.
**Git Push: Git**: **Click Push** to Push changes to the remote repository.
**Git Commit:** **Git**: **Click Commit** to Commit the staged changes with a commit message.
**Git Branch:** **Git:** **Click Create** a **Branch** to Create a new Git branch.

### **Extensions and Marketplace:**

**Install Extension**: **Extensions**: an **Icon that looks like three boxes** to **Install Extensions** Open the extension Marketplace. Search and install extensions from the VS Code marketplace.
**Show Installed Extensions**: **Extensions**: **Show Installed Extensions** - Lists all installed extensions.
**Enable/Disable Extension:** You can enable or disable extensions via the Command Palette.

### **Integrated Terminal:**

**New Terminal:** **Go to File**, **Click on Terminal**, then **New Terminal** to open a new integrated terminal. The Terminal accepts **Git commands** such as **git add <filename>**, **git commit**, **git push, git pull**, etc.
The workspace terminal also accepts bash commands such as **cd, ls, pwd, touch, mkdir**, etc.

**Conclusion**

**Wagtail gives developers a complete tool to customize your site or play around with the code.**

**Comment by Ozyugoo** [comment]
>@thibaudcolas Kindly review
Thank you.

**Comment by thibaudcolas** [comment]
@Ozyugoo the command palette isn’t even a feature of Wagtail yet, this is only a proposed feature. Please take more time to understand the CMS before going through this – what you’re documenting here is GitPod, which has nothing to do with Wagtail.
