### ISSUE TITLE
Session Time Limit

### ISSUE THREAD

**Issue by Ennymama** [wagtail/guide#352]
Certain webpages feature time limits that give users a set amount of time to engage with the content. For security reasons, websites containing forms and those requiring a login, for instance, typically have time restrictions.  It's critical that when a time limit is in place, the user is given the opportunity to extend the time allotted to finish their task and receives a proper time response notification. The following rules should be adhered to in order to guarantee timely responses:

Users should receive a time out notification when their session is about to expire.
When a user receives a time-out notification, they should move their focus to the dialogue box containing the time-out notification.

A reasonable amount of time should be allowed to users before the time-out signals the end of a session. For instance, the user is not given enough time to comprehend and respond to a time-out notification if it appears and the page closes shortly after, signalling that the session is about to expire.

After receiving a time-out notification, if a user decides to continue, their focus should revert to the part of the page where the timed response message was originally displayed.

Time extension: It should be possible for users to change and extend the time limit settings.

**Comment by thibaudcolas** [comment]
@Ennymama 👋  I don’t totally understand what your issue is about? This repository is about documentation for [Wagtail](https://wagtail.org/), I’m not sure whether your issue is about another project altogether or just the wrong repository, or what you are suggesting.

**Comment by Ennymama** [comment]
Sorry @thibaudcolas ....my bad...this is a documentation for Session Time Limit on Wagtail's website as identified here as an accessibility feature needing documentation: 
<img width="1680" alt="Screenshot 2023-11-04 at 17 25 42" src="https://github.com/wagtail/guide/assets/147211636/3016f2c9-dd41-40bd-912f-60b00bc31b49">

**Comment by thibaudcolas** [comment]
Thanks. Wagtail has no time-out notifications as you describe so this was very confusing. We already have issue #365 to describe how the session timeout works, so I’ll keep this closed.
