### ISSUE TITLE
No documentation found on minimap feature

### ISSUE THREAD

**Issue by ArafatAbdussalam** [wagtail/guide#355]
## **What is a minimap**

The minimap feature represents different sections of the page while in editing-view. It allows content authors to be able to quickly navigate to a particular section of the webpage

## **Why do we need to document the minimap feature**

Authors might find it confusing understanding what the lines in the right-hand side of the page actually mean. Despite clicking on the lines, they might still not understand what it is responsible for. To document the features means that the authors have a resource which allows them to understand the sole purpose of the minimap feature and other possible activities that can be done with it.

## **Suggested Documentation content for the minimap feature**

![minimap](https://github.com/wagtail/guide/assets/92020171/41496c36-351c-4d3b-bb98-5ca187d2d928)

**Comment by ArafatAbdussalam** [comment]
![minimap 2](https://github.com/wagtail/guide/assets/92020171/9e376c16-8230-457a-9a98-a338e48fa5e2)

**Comment by thibaudcolas** [comment]
@ArafatAbdussalam thank you for taking a look at this. I’ll close this in favour of #345 which as created before. Note we can’t have the documentation be so dependent on screenshots.

**Comment by ArafatAbdussalam** [comment]
Okay. That is noted. Thank you.
