### ISSUE TITLE
Update focus style to follow WCAG guidelines

### ISSUE THREAD

**Issue by thibaudcolas** [wagtail/guide#36]
The current focus style is #b8cfd5 over #EDEAF3, which isn’t enough contrast ([contrast grid](https://contrast-grid.eightshapes.com/?version=1.1.0&background-colors=&foreground-colors=%23EDEAF3%0D%0A%23B8CFD5&es-color-form__tile-size=compact&es-color-form__show-contrast=aaa&es-color-form__show-contrast=aa&es-color-form__show-contrast=aa18&es-color-form__show-contrast=dnp)) to pass accessibility checks. We need to switch to another color that has at least 3:1 contrast against all backgrounds where the focus would appear.

**Comment by lb-** [comment]
Should we make it 1px thicker also?

**Comment by nicklee** [comment]
Added here: https://github.com/wagtail/guide/pull/148
