### ISSUE TITLE
Images and third party scripts are not loading (CSP)

### ISSUE THREAD

**Issue by lb-** [wagtail/guide#384]
Raised in Slack but I have just validated myself and can also see that images are not loading. https://wagtailcms.slack.com/archives/C044M905R9D/p1700329211849159

> FYI, the user guide is failing to load images in many pages (e.g. https://guide.wagtail.org/en-latest/releases/new-in-wagtail-5-2/) with these kinds of errors:
> Refused to load the image '<URL>' because it violates the following Content Security Policy directive: "img-src 'self'  data:  <URL>".
> new-in-wagtail-5-2/:556 Refused to load the image 'https://guide-media.wagtail.org/images/page-listing-redesigned.width-900.png' because it violates the following Content Security Policy directive: "img-src 'self'  data:  https://www.gravatar.com".
> Refused to load the script 'https://static.cloudflareinsights.com/beacon.min.js/v84a3a4012de94ce1a686ba8c167c359c1696973893317' because it violates the following Content Security Policy directive: "script-src 'self'  'unsafe-inline'". Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback.

## Screenshot 

![Screenshot_20231119-070740](https://github.com/wagtail/guide/assets/1396140/f64fba4f-4637-4c2f-9775-011faa1e5037)

**Comment by allcaps** [comment]
I've changed the SCP env variable settings on Heroku from
```CSP_IMG_SRC='self', data:, https://www.gravatar.com```
to
```CSP_IMG_SRC='self', data:, https://www.gravatar.com, https://guide-media.wagtail.org```
And resolved the issue.

Not sure if we'd like to revisit other SCP changes, so leaving this open until after the weekend. So that @thibaudcolas and @Tijani-Dia can have a proper look.

**Comment by lb-** [comment]
Thanks @allcaps - I can see that images are working now.

**Comment by thibaudcolas** [comment]
Thanks all!
