### ISSUE TITLE
Set up wagtail-localize for translations

### ISSUE THREAD

**Issue by thibaudcolas** [wagtail/guide#62]
Once we definitely want to have translations, we need to set up <https://github.com/wagtail/wagtail-localize>. cc @kaedroho whom we will want to get involved to review our setup.

**Comment by allcaps** [comment]
We need versioning. Can we keep special locales for versions?  

I'm not sure if Wagtail Localize can handle the special locales. Eg `en-latest` or `en-4.0.0`. I never tried it. But I needed to patch Django and Wagtail Simple Translation to make this work.
