### ISSUE TITLE
Add the ability to thank content contributors

### ISSUE THREAD

**Issue by lb-** [wagtail/guide#66]
It would be great if we had the ability to make content contributions visible to the community.

It's important to thank those that contribute and it's also a small way to acknowledge them in public.

I know the current guide has a footer call out to the copyright, maybe this is better served with a call out to the core contributors and content contributors. 

## Proposal - thanks page

- This would be a standard page on the root that contains some body content with a special call out the the history of this project (link to Blog posts etc) and to @Hitansh-Shah 
- It would also have an auto-generated list of unique names of users that have contributed in reverse chronological order.
- Maybe users can opt out of being on this list on their user settings and also provide a name they want listed (e.g. they may want to call out their company or nickname) 

## Proposal - names added to contributors.md

- As per the Wagtail package guidelines we should have a contributors markdown file in this project's root (I know this is not a package you use in projects but it's similar)
- Similar to how Wagtail includes the translators and code contributors it would be good to add those names to the code repo as a seperate section (could be updated each time Wagtail does a major/minor bump & we do the page creation stuff for a new release).

**Comment by thibaudcolas** [comment]
For the time being I’ve made this as manually-updated sections of the "About" page: https://guide.wagtail.org/en-latest/about/

What do you think LB? Should we automate this further or leave it at that?

**Comment by lb-** [comment]
Manual process is a good process - we can automate this later if the need arises. Thanks!

Love the little shout out on the list 
> You?.. contribute link

A nice touch.
