### ISSUE TITLE
Guidance on how to translate to a new language

### ISSUE THREAD

**Issue by lb-** [wagtail/guide#67]
### Discussed in https://github.com/wagtail/guide/discussions/65

<div type='discussions-op-text'>

<sup>Originally posted by **saevarom** September 10, 2022</sup>
I am interested in translating the guide to my native language, Icelandic.

I get the impression that the methods for translating content is still under development, but I'm interested in what the plans are for translating content going forward?

Will you have translation teams for each language? Something like the translation teams in Transifex?</div>

**Comment by thibaudcolas** [comment]
I’ve added a brief description of the setup on https://guide.wagtail.org/en-latest/contributing/#translations. We’ll see how that goes and might make more changes / further document the process later on.

**Comment by f4biosa** [comment]
I saw that it is already possible to translate, I want to contribute with Brazilian Portuguese.

I've already downloaded the code and I'm managing to translate it on my machine, can I just send the .po files to the repository or do I also need a profile on the guide's website?

**Comment by lb-** [comment]
@f4biosa the guide content is translated within the Wagtail admin of the guide. 

If you want to translate content that is within the admin interface, that's where you use transifex and .po.files. 

What content are you wanting to translate? Guide content or admin interface content?
