### ISSUE TITLE
Add page for contributing to the guide

### ISSUE THREAD

**Issue by lb-** [wagtail/guide#68]
Flagging that the link to help improve this guide does not go anywhere yet.

<img width="382" alt="Screen Shot 2022-09-20 at 7 35 20 am" src="https://user-images.githubusercontent.com/1396140/191124089-444c906b-7af4-46f0-b7e9-1e6e0444ad28.png">

We should add this page and also call out this Guide contribution on the main Wagtail docs above 'Other contributions'.

https://docs.wagtail.org/en/stable/contributing/index.html#other-contributions

Additional to providing details on how to translate, we should really provide details on how to create an account and start contributing https://github.com/wagtail/guide/issues/67

**Comment by thibaudcolas** [comment]
@lb- thanks LB. The site is still under development with partly implemented front-end, content, back-end – so it’s expected for now that there will be gaps in implementation. And right now we’re not at a place where we can solicit contributions yet.

**Comment by lb-** [comment]
Makes sense. Thanks Thibaud

**Comment by thibaudcolas** [comment]
I’ve made a very simple page for the time being: https://guide.wagtail.org/en-latest/contributing/

Will ad this to the footer once #78 is done.
