### ISSUE TITLE
Accessibility check by Wagtail a11y team

### ISSUE THREAD

**Issue by thibaudcolas** [wagtail/guide#76]

**Comment by Scotchester** [comment]
Will edit the above original post to add a checklist of found issues, then decide whether to break them out into their own individual issues.

**Comment by Scotchester** [comment]
My review is complete! The original post has been updated with all of my findings. @thibaudcolas It seems like perhaps too many to bother with making individual issues for all of them. Maybe we get the low-hanging fruit first, and then create issues for any that we need to put off until after launch?

**Comment by thibaudcolas** [comment]
Sounds great to me @Scotchester, thank you

**Comment by thibaudcolas** [comment]
Feeling a bit procedural here but I’ve moved the issues to #179 so I can mark the auditing as "done" 👀 ✅
